# Generated by Django 5.1.5 on 2025-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.JSONField()),
                ('workExperience', models.JSONField()),
                ('qualifications', models.JSONField()),
                ('projects', models.JSONField()),
                ('photo', models.TextField(blank=True)),
            ],
        ),
    ]
